# Bradley 19/12/25
import os
configfile: "configs/config.yaml"

# Load gene names
with open(config["gene_file"], "r") as f:
    genes = [line.strip() for line in f if line.strip()]

# Load celltypes
with open(config["celltypes"], "r") as f:
    celltypes = [line.strip() for line in f if line.strip()]

# Dynamically determine memory
def mem_from_input(input_file, multiplier=10, min=4000):
    """Return memory in MB as input_file_size_GB × multiplier × 1024."""
    size_bytes = os.path.getsize(input_file)
    size_gb = size_bytes / (1024**3)
    mem_mb = int(size_gb * multiplier * 1024)
    # enforce a reasonable minimum
    return max(mem_mb, min)

##########
# Rule all
##########
def gather_cs_per_gene(wildcards):
    return expand("results/finemapping/{gene}/{celltype}.crediblesets.txt", gene = wildcards.gene, celltype=celltypes)

rule all:
    input:
         expand("results/coloc/{gene}_coloc_postfinemap.txt", gene=genes),
         expand("results/coloc/{gene}_pairwise_coloc_results.txt", gene=genes)

##########
# Rules
###########

rule prep_genotypes:
    output:
        "input/LDmatrix/{gene}.ld"
    params:
        vcf=config["VCF_FILE"],
        gene_file=config["gene_file"]
    resources:
        mem=lambda wildcards, attempt: 3000 * (2 ** (attempt - 1)),
        mem_mb=lambda wildcards, attempt: 3000 * (2 ** (attempt - 1)),
        mem_mib=lambda wildcards, attempt: 3000 * (2 ** (attempt - 1)),
        disk_mb=lambda wildcards, attempt: 3000 * (2 ** (attempt - 1)),
    singularity:
        "/software/hgi/softpack/installs/users/bh18//finemapping/3-scripts/singularity.sif"
    shell:
        r"""
            mkdir -p input/{{vcf,LDmatrix}}
            mkdir -p results/finemapping
            mkdir -p logs
            Rscript scripts/get_gene_window.r {wildcards.gene} {wildcards.gene}
            
            # Then prep the genotypes
            filt_vcf="input/vcf/{wildcards.gene}_"
            LD_file_pref="input/LDmatrix/{wildcards.gene}"
            region_file="input/vcf/{wildcards.gene}_gene_window.txt"
            bash scripts/filter_vcf_by_region-compute_LD.sh {params.vcf} "$region_file" "$filt_vcf" "$LD_file_pref"
        """    

rule run_susie:
    input:
        "input/LDmatrix/{gene}.ld"
    output:
        "results/finemapping/{gene}/{celltype}.crediblesets.txt"
    params:
        eqtl_dir=config["eqtl_dir"]
    resources:
        mem=lambda wildcards, input, attempt: mem_from_input(input[0], multiplier=6, min=8000),
        mem_mb=lambda wildcards, input, attempt: mem_from_input(input[0], multiplier=6, min=8000),
        mem_mib=lambda wildcards, input, attempt: mem_from_input(input[0], multiplier=6, min=8000),
        disk_mb=lambda wildcards, input, attempt: mem_from_input(input[0], multiplier=6, min=8000)
    singularity:
        "/software/hgi/softpack/installs/users/bh18//finemapping/5-scripts/singularity.sif"
    shell:
        r"""
            SAMPLESIZE=$(awk '{{print NF-1; exit}}' {params.eqtl_dir}/dMean__{wildcards.celltype}_all/OPTIM_pcs/base_output/base/Covariates.tsv)
            echo "SAMPLESIZE: " ${{SAMPLESIZE}}
            chr=$(awk -F'\t' 'NR==1{{sub(/^chr/,"",$1); print $1}}' input/vcf/{wildcards.gene}_gene_window.txt)
            echo "chr: " ${{chr}}

            Rscript scripts/runsusie.r \
                    {wildcards.gene} \
                    {params.eqtl_dir}/dMean__{wildcards.celltype}_all/OPTIM_pcs/base_output/base/cis_nominal1.cis_qtl_pairs.${{chr}}.tsv \
                    ${{SAMPLESIZE}} \
                    {input} \
                    input/vcf/{wildcards.gene}_.z \
                    results/finemapping/{wildcards.gene}/{wildcards.celltype}.
            
        """
        
rule coloc_postfinemap:
    input:
        gather_cs_per_gene
    output:
        "results/coloc/{gene}_coloc_postfinemap.txt",
        "results/coloc/{gene}_pairwise_coloc_results.txt"
    params:
        colocthresh=config["colocthresh"]
    resources:
        mem=lambda wildcards, attempt: 10000 * (2 ** (attempt - 1)),
        mem_mb=lambda wildcards, attempt: 10000 * (2 ** (attempt - 1)),
        mem_mib=lambda wildcards, attempt: 10000 * (2 ** (attempt - 1)),
        disk_mb=lambda wildcards, attempt: 10000 * (2 ** (attempt - 1))
    singularity:
        "/software/hgi/softpack/installs/users/bh18//finemapping/5-scripts/singularity.sif"
    shell:
        r"""
            mkdir -p results/coloc
            Rscript scripts/get_eQTL_coloc_networks.r \
                {wildcards.gene} \
                "results/finemapping/{wildcards.gene}" \
                "input/LDmatrix/{wildcards.gene}.ld" \
                "input/vcf/{wildcards.gene}_.z" \
                {params.colocthresh}
        """
    